[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}\
### {{ group }}

{% for commit in commits %}\
- {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message | upper_first }} \
([`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/MoKhajavi75/matchday/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}\
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true

commit_parsers = [
  { message = "^feat", group = "ğŸš€ Features" },
  { message = "^fix", group = "ğŸ› Bug Fixes" },
  { message = "^perf", group = "âš¡ Performance" },
  { message = "^refactor", group = "ğŸ”§ Refactoring" },
  { message = "^docs", group = "ğŸ“š Documentation" },
  { message = "^style", group = "ğŸ¨ Styling" },
  { message = "^test", group = "ğŸ§ª Testing" },
  { message = "^chore|^ci|^build", group = "ğŸ”© General" }
]

filter_commits = false
tag_pattern = "v[0-9].*"
